### ISSUE TITLE
Scavenger Hunt Entry: Hoang Do

### ISSUE THREAD

**Issue by KhanhDoHoang** [education/hackconviii#10]
**Say hello 👋**
- [x] Yes, I have said hello to everyone I know at HackCon VIII

**Make new friends 👯‍♀️**
Share a screenshot of you introducing yourself to someone new.

![Hackon1](https://user-images.githubusercontent.com/55791090/90956768-87366c80-e457-11ea-824c-2a0de6e295e4.PNG)

**Build your alter ego Octocat**
Please upload your Octocat here.
![octocat](https://user-images.githubusercontent.com/55791090/90956773-90273e00-e457-11ea-93e1-e4adc452fe48.png)

**Screenshot selfie**
Upload the selfie of you and a GitHub team member or Campus Expert here.
![Hackon3](https://user-images.githubusercontent.com/55791090/90956893-776b5800-e458-11ea-83ec-e1a782fb0524.PNG)

**Show us your "view" 🖼**
- [x] I've uploaded my view to the Discussion

**Where in the world? 🌍**
- [x] I've uploaded a picture to the Discussion

**Attend at least one lightning talk or panel featuring a Campus Expert ⚡️**
Which talk did you attend?
Tell us a little bit about something you learned or were surprised by.

🥚
Share with us a screenshot of what you found 😁 be sure to include your computer's clock in the screenshot to verify you've found the surprise yourself 🎉
- [x]  I have shared a screenshot of the 🥚 with @elisemoe on Discord

**Comment by elisemoe** [comment]
Be sure to finish before 12pm PT (in 1.5 hours) to enter the raffle! ✨
