### ISSUE TITLE
Scavenger Hunt Entry: Hrithik Sahu

### ISSUE THREAD

**Issue by HrithikSahu** [education/hackconviii#11]
**Say hello 👋**
- [x] Yes, I have said hello to everyone I know at HackCon VIII

**Make new friends 👯‍♀️**
<img width="295" alt="Capture1" src="https://user-images.githubusercontent.com/61985253/90961287-702e6380-e4c5-11ea-8ae2-fd33dcb9341b.PNG">

**Build your alter ego Octocat**
![octocat](https://user-images.githubusercontent.com/61985253/90960405-e7acc480-e4be-11ea-95a7-288521fb1deb.png)

**Screenshot selfie**
![Screenshot (228)](https://user-images.githubusercontent.com/61985253/90963470-7d534e80-e4d5-11ea-9c77-0d7723f2bf22.png)

**Show us your "view" 🖼**
- [x] I've uploaded my view to the Discussion

**Where in the world? 🌍**
- [x] I've uploaded a picture to the Discussion

**Attend at least one lightning talk or panel featuring a Campus Expert ⚡️**
Which talk did you attend?
Tell us a little bit about something you learned or were surprised by.
I Attended An lightning talk where yash was live. And one thing i found most Interesting was that - Hackathons were always meant to be about Learning , Connecting with new People and Enjoying the process. But nowadays it has become an rigorous Competition where you'll have to participate to win. Not gonna lie I too somewhat thought the same when i started out, but after a Few Hackathons i realised It's all about the Fun and Learn rather Winning. 
Winning comes around if you do better at Learning. 

🥚
Share with us a screenshot of what you found 😁 be sure to include your computer's clock in the screenshot to verify you've found the surprise yourself 🎉

Yayy DID IT.

**Comment by elisemoe** [comment]
Congrats @HrithikSahu   ✨ You've completed your missions and can advance to the final stage 🎟. The GitHub stage! Please stop by the [GitHub Expo booth](https://app.hopin.to/events/hackcon-viii/expo/95842) anytime we’re not in session (or when the video is running) and request to share audio and video. We’ll invite you onto the stage and would love to either,

1. Hear your favorite programming joke, or
2. See your favorite dance move

If you don't hear from us right away, be sure to ping us in the #github-at-hackcon channel. Completion of this task will enter you into the raffle for scavenger hunt prizes.

See you there 💖
