### ISSUE TITLE
Scavenger Hunt Entry: Sanjay Charles

### ISSUE THREAD

**Issue by charliebaer** [education/hackconviii#12]
**Say hello 👋**
- [x] Yes, I have said hello to everyone I know at HackCon VIII

**Make new friends 👯‍♀️**
![mlh intro](https://user-images.githubusercontent.com/50674268/90957305-50d60d00-e4aa-11ea-84be-ab4a37e4e3be.png)

**Build your alter ego Octocat**
<img src="https://user-images.githubusercontent.com/50674268/90957462-4d8f5100-e4ab-11ea-96f2-b10385a373bf.png" width="500" height="500">

**Screenshot selfie**
Upload the selfie of you and a GitHub team member or Campus Expert here.
I'm here all by myself <3

**Show us your "view" 🖼**
- [x] I've uploaded my view to the Discussion

**Where in the world? 🌍**
- [x] I've uploaded a picture to the Discussion

**Attend at least one lightning talk or panel featuring a Campus Expert ⚡️**
Which talk did you attend?
Tell us a little bit about something you learned or were surprised by.

🥚
Share with us a screenshot of what you found 😁 be sure to include your computer's clock in the screenshot to verify you've found the surprise yourself 🎉

**Comment by elisemoe** [comment]
@charliebaer Be sure to finish before 12pm PT (in 1.5 hours) to enter the raffle! ✨
