### ISSUE TITLE
Scavenger Hunt Entry: Jay Patel

### ISSUE THREAD

**Issue by jaypatel15406** [education/hackconviii#13]
**Say hello 👋**
- [x] Yes, I have said hello to everyone I know at HackCon VIII

**Make new friends 👯‍♀️**
![Introduction](https://user-images.githubusercontent.com/50138179/90960448-39554f00-e4bf-11ea-9337-e9c2acbc0d3f.PNG)

**Build your alter ego Octocat**
![octocat](https://user-images.githubusercontent.com/50138179/90960452-407c5d00-e4bf-11ea-9bf8-b04321153c2a.png)

**Screenshot selfie**
![GitHub Network (1)](https://user-images.githubusercontent.com/50138179/90960459-46723e00-e4bf-11ea-9e21-47da3cd4ee9e.png)

**Show us your "view" 🖼**
- [x] I've uploaded my view to the Discussion

**Where in the world? 🌍**
- [x] I've uploaded a picture to the Discussion

**Attend at least one lightning talk or panel featuring a Campus Expert ⚡️**
Which talk did you attend?
I have Attended **Organizer Hangouts #1** By Expert Panelist @juanpflores @jch and Other 3 Speakers. The Key Point to Take Away from this was How you can Conduct Successful Hackathon and Much More. I have also Connected to Many Devs and Expect to Learn from them a Lot :)
I have also Attended Keynote By @juanpflores and also I have Attended an Extra-Ordinary Kahoot Organize By @juanpflores and 2 Expert Speakers. I have Enjoyed it a Lot 💯 👍 
Looking forward to More Sessions MLH HackCon is Going on Very Well and It was Such an Informative Sessions !!! 👍 

🥚
Share with us a screenshot of what you found 😁 to be sure to include your computer's clock in the screenshot to verify you've found the surprise yourself 🎉

**Comment by elisemoe** [comment]
Congrats ✨ You've completed your missions and can advance to the final stage 🎟. The GitHub stage! Please stop by the [GitHub Expo booth](https://app.hopin.to/events/hackcon-viii/expo/95842) anytime we’re not in session (or when the video is running) and request to share audio and video. We’ll invite you onto the stage and would love to either,

1. Hear your favorite program joke, or
2. See your favorite dance move

Completion of this task will enter you into the raffle for scavenger hunt prizes.

See you there 💖
