### ISSUE TITLE
Scavenger Hunt Entry: Chee Seng Leong

### ISSUE THREAD

**Issue by csleong98** [education/hackconviii#14]
- [x]  Yes, I have said hello to everyone I know at HackCon VIII

**Make new friends 👯‍♀️**
We were talking about our own respective hackathons in Hopin but suddenly it ran out of time so we continue here.
<img width="1722" alt="Screen Shot 2020-08-22 at 8 31 19 PM" src="https://user-images.githubusercontent.com/6150058/90960605-5e54bc80-e4d5-11ea-8b2e-fd44aa8a3b29.png">

**Build your alter ego Octocat**
Please upload your Octocat here.
If I am an Octocat, I would wanna be an astroOctocat holding a blackhole
![csleong98-octocat](https://user-images.githubusercontent.com/6150058/90960623-86dcb680-e4d5-11ea-95f8-0059b84815f0.png)

**Screenshot selfie**
Me n the boys and girls
<img width="1571" alt="Screen Shot 2020-08-22 at 9 13 49 PM" src="https://user-images.githubusercontent.com/6150058/90960791-bf30c480-e4d6-11ea-80a8-be31f0f95e50.png">

**Show us your "view" 🖼**

- [x]  I've uploaded my view to the Discussion

**Where in the world? 🌍**

- [x]  I've uploaded my picture to the Discussion

**Attend at least one lightning talk or panel featuring a Campus Expert ⚡️**
Attended a session known as Building a collaboration culture through CI/CD by Carlo Gilmar a Github CE. I am a designer and know nothing about CI/CD. This is a good and simple introduction to know that as a designer I am part of the process and the tools available. Also, even though there are many tools. The main thing is communication with other stakeholders.

🥚
Share with us a screenshot of what you found 😁 be sure to include your computer's clock in the screenshot to verify you've found the surprise yourself 🎉

**Comment by elisemoe** [comment]
Congrats @csleong98  ✨ You've completed your missions and can advance to the final stage 🎟. The GitHub stage! Please stop by the [GitHub Expo booth](https://app.hopin.to/events/hackcon-viii/expo/95842) anytime we’re not in session (or when the video is running) and request to share audio and video. We’ll invite you onto the stage and would love to either,

1. Hear your favorite programming joke, or
2. See your favorite dance move

Completion of this task will enter you into the raffle for scavenger hunt prizes.

See you there 💖
