### ISSUE TITLE
Scavenger Hunt Entry: Yashraj Nayak

### ISSUE THREAD

**Issue by yashrajnayak** [education/hackconviii#15]
**Say hello 👋**
- [ ] Yes, I have said hello to everyone I know at HackCon VIII

**Make new friends 👯‍♀️**
Share a screenshot of you introducing yourself to someone new.

**Build your alter ego Octocat**
Please upload your Octocat here.

**Screenshot selfie**
Upload the selfie of you and a GitHub team member or Campus Expert here.

I met Ashley Bass from GitHub and had a great discussion around communities, programs at GitHub, etc.
![image](https://user-images.githubusercontent.com/10005645/90963681-762d4000-e4d7-11ea-8782-96dc57ce49ff.png)

**Show us your "view" 🖼**
- [ ] I've uploaded my view to the Discussion

**Where in the world? 🌍**
- [ ] I've uploaded a picture to the Discussion

**Attend at least one lightning talk or panel featuring a Campus Expert ⚡️**
Which talk did you attend?
Tell us a little bit about something you learned or were surprised by.

🥚
Share a screenshot of what you found with `@elisemoe from Github` on Discord 😁 be sure to include your computer's clock in the screenshot to verify you've found the surprise yourself 🎉

- [ ] I have shared a screenshot of the 🥚 with @elisemoe on Discord

**Comment by elisemoe** [comment]
@yashrajnayak Be sure to finish before 12pm PT (in 1.5 hours) to enter the raffle! ✨
