### ISSUE TITLE
Scavenger Hunt Entry: Anna Arroyo (discord: imannajourney#4411)

### ISSUE THREAD

**Issue by annaarroyo** [education/hackconviii#16]
**Say hello 👋**
- [x] Yes, I have said hello to everyone I know at HackCon VIII
i said hi to elisemoe from GitHub on the github channel :)
my username is imannajourney#4411

**Make new friends 👯‍♀️**
Share a screenshot of you introducing yourself to someone new.
![image](https://user-images.githubusercontent.com/43049986/90963677-684bd080-e47f-11ea-9ec8-8b0f805ead3a.png)

**Build your alter ego Octocat**
Please upload your Octocat here.

![octocat](https://user-images.githubusercontent.com/43049986/90963847-fbd1d100-e480-11ea-92c0-430f234d0325.png)

**Screenshot selfie**
Upload the selfie of you and a GitHub team member or Campus Expert here.

Me and Otavio from Brazil!!!

<img width="960" alt="me-and-otavio" src="https://user-images.githubusercontent.com/43049986/90963603-b3191880-e47e-11ea-8b48-f582aeffa3d8.png">

**Show us your "view" 🖼**
- [x] I've uploaded my view to the Discussion

**Where in the world? 🌍**
- [x] I've uploaded a picture to the Discussion

**Attend at least one lightning talk or panel featuring a Campus Expert ⚡️**
Which talk did you attend?
I attended GitHub Lounge Activity: GitHub Engineering Q&A

Tell us a little bit about something you learned or were surprised by.
I was learned how diverse coders can be and how much of a good thing that can be as well. Hearing from Laura and Stephanie and how they had such different paths to the tech world makes me feel better about my path. Laura talking about her experience as a biologist and noticing similarities between those practices and software engineering practices makes me realize that coming from different and diverse backgrounds makes the workplace a better space with unique ideas and individuals. We should embrace our backgrounds and uniqueness.

🥚
Share a screenshot of what you found with `@elisemoe from Github` on Discord 😁 be sure to include your computer's clock in the screenshot to verify you've found the surprise yourself 🎉

- [x] I have shared a screenshot of the 🥚 with @elisemoe on Discord

**Comment by elisemoe** [comment]
Congrats @annaarroyo   ✨ You've completed your missions and can advance to the final stage 🎟. The GitHub stage! Please stop by the [GitHub Expo booth](https://app.hopin.to/events/hackcon-viii/expo/95842) anytime we’re not in session (or when the video is running) and request to share audio and video. We’ll invite you onto the stage and would love to either,

1. Hear your favorite programming joke, or
2. See your favorite dance move

If you don't hear from us right away, be sure to ping us in the #github-at-hackcon channel. Completion of this task will enter you into the raffle for scavenger hunt prizes.

See you there 💖

**Comment by annaarroyo** [comment]
done! thanks for the fun :)
