### ISSUE TITLE
Scavenger Hunt Entry: Vikramaditya Jaisingh

### ISSUE THREAD

**Issue by TheVikJ** [education/hackconviii#17]
**Say hello 👋**
- [ ✔] Yes, I have said hello to everyone I know at HackCon VIII

**Make new friends 👯‍♀️**
Share a screenshot of you introducing yourself to someone new.
![Capture](https://user-images.githubusercontent.com/33194767/90954914-7fe28380-e496-11ea-9fdc-d07afc9f3cf7.PNG)

**Build your alter ego Octocat**
Please upload your Octocat here.
![octocat](https://user-images.githubusercontent.com/33194767/90954921-883abe80-e496-11ea-91a5-1200fd75d124.png)

**Screenshot selfie**
Upload the selfie of you and a GitHub team member or Campus Expert here.

![IMG_20200822_203522](https://user-images.githubusercontent.com/33194767/90962668-52fe9280-e4cf-11ea-8f75-07e2b8af6ed9.jpg)

Juan P Flores 😮😮

**Show us your "view" 🖼**
- [✔ ] I've uploaded my view to the Discussion

![IMG_20200822_232358__01](https://user-images.githubusercontent.com/33194767/90962657-3f532c00-e4cf-11ea-99a6-dfaccffe95cb.jpg)

**Where in the world? 🌍**
- [✔ ] I've uploaded a picture to the Discussion
New Delhi, India
![download](https://user-images.githubusercontent.com/33194767/90962608-103cba80-e4cf-11ea-81ed-1c1bccd9418b.jpg)

**Attend at least one lightning talk or panel featuring a Campus Expert ⚡️**
Which talk did you attend?
Tell us a little bit about something you learned or were surprised by.

I attended the GitHub Interns Panel. Cool stories, definitely made me want to apply in 2 years (when I graduate High School).

🥚
Share with us a screenshot of what you found 😁 be sure to include your computer's clock in the screenshot to verify you've found the surprise yourself 🎉
![Capture](https://user-images.githubusercontent.com/33194767/90965505-53eeee80-e4e6-11ea-9a42-6200720dca48.PNG)
This took me extremely, embarrassingly long lmao. I thought that the shading on the Hackathon board on the site (made of lines and dots), was morse code. Then, I got 4 random letters which I though spelt Mona in some cipher. I am so stupid lmao but as elisemoe said, at least you guys have ideas for next time 😂😂😂

Also, this event was so fun!! Enjoyed every activity! 😄

**Comment by elisemoe** [comment]
Congrats @Vik0105   ✨ You've completed your missions and can advance to the final stage 🎟. The GitHub stage! Please stop by the [GitHub Expo booth](https://app.hopin.to/events/hackcon-viii/expo/95842) anytime we’re not in session (or when the video is running) and request to share audio and video. We’ll invite you onto the stage and would love to either,

1. Hear your favorite programming joke, or
2. See your favorite dance move

If you don't hear from us right away, be sure to ping us in the #github-at-hackcon channel. Completion of this task will enter you into the raffle for scavenger hunt prizes.

See you there 💖
