### ISSUE TITLE
Scavenger Hunt Entry: Michael Taylor

### ISSUE THREAD

**Issue by mike-taylor99** [education/hackconviii#18]
**Say hello 👋**
- [x] Yes, I have said hello to everyone I know at HackCon VIII

**Make new friends 👯‍♀️**
Share a screenshot of you introducing yourself to someone new.
![image](https://user-images.githubusercontent.com/47544533/90965620-e3b97c00-e497-11ea-936a-83a558bdeecb.png)

**Build your alter ego Octocat**
Please upload your Octocat here.
![octocat](https://user-images.githubusercontent.com/47544533/90965681-69d5c280-e498-11ea-8927-c9b41739e3f4.png)

**Screenshot selfie**
Upload the selfie of you and a GitHub team member or Campus Expert here.
![image](https://user-images.githubusercontent.com/47544533/90966030-e5853e80-e49b-11ea-9b3f-e39b88c00ce3.png)

**Show us your "view" 🖼**
- [x] I've uploaded my view to the Discussion

**Where in the world? 🌍**
- [x] I've uploaded a picture to the Discussion

**Attend at least one lightning talk or panel featuring a Campus Expert ⚡️**
Which talk did you attend?
Tell us a little bit about something you learned or were surprised by.

I attended GitHub Lounge: GitHub Interns Panel. I got to hear from GitHub interns on their experiences such as Jorge who completed his internship from Spain. I also got more insights into the Campus Experts Program which I am currently in the training process for.

🥚
Share a screenshot of what you found with `@elisemoe from Github` on Discord 😁 be sure to include your computer's clock in the screenshot to verify you've found the surprise yourself 🎉

- [x] I have shared a screenshot of the 🥚 with @elisemoe on Discord

**Comment by elisemoe** [comment]
Congrats @mike-taylor99   ✨ You've completed your missions and can advance to the final stage 🎟. The GitHub stage! Please stop by the [GitHub Expo booth](https://app.hopin.to/events/hackcon-viii/expo/95842) anytime we’re not in session (or when the video is running) and request to share audio and video. We’ll invite you onto the stage and would love to either,

1. Hear your favorite programming joke, or
2. See your favorite dance move

If you don't hear from us right away, be sure to ping us in the #github-at-hackcon channel. Completion of this task will enter you into the raffle for scavenger hunt prizes.

See you there 💖
