### ISSUE TITLE
Scavenger Hunt Entry: Raymond Li

### ISSUE THREAD

**Issue by Raymo111** [education/hackconviii#19]
**Say hello 👋**
- [x] Yes, I have said hello to everyone I know at HackCon VIII

**Make new friends 👯‍♀️**
<img src=https://user-images.githubusercontent.com/34818275/90966636-bd4d0e00-e4a2-11ea-9dee-68072e1fae6c.png height="600">

**Build your alter ego Octocat**
![octocat](https://user-images.githubusercontent.com/34818275/90966717-cbe7f500-e4a3-11ea-9ae7-941a6cb41130.png)

**Screenshot selfie**
![image](https://user-images.githubusercontent.com/34818275/90966979-c809a200-e4a6-11ea-80d1-27f8252923bb.png)

**Show us your "view" 🖼**
- [x] I've uploaded my view to the Discussion

**Where in the world? 🌍**
- [x] I've uploaded a picture to the Discussion

**Attend at least one lightning talk or panel featuring a Campus Expert ⚡️**
*Which talk did you attend?*
Why hacking shouldn't end when hackers become organizers

*Tell us a little bit about something you learned or were surprised by:*
That hackathons shouldn't just be about participants! I'm definitely taking a bit of time at future hackathons that I organize to network with organizers too!

🥚
Share a screenshot of what you found with `@elisemoe from Github` on Discord 😁 be sure to include your computer's clock in the screenshot to verify you've found the surprise yourself 🎉
- [x] I have shared a screenshot of the 🥚 with @elisemoe on Discord

**Comment by elisemoe** [comment]
Congrats @Raymo111   ✨ You've completed your missions. I'd invite you to the final GitHub stage 🎟. but since you've already shared an incredible joke, you're all good to good 😅  I've entered you in the raffle for tomorrow.

**Comment by Raymo111** [comment]
Thank you so much! I didn't know that was the final mission LOL (had much fun anyway) P.S. I love jokes

**Comment by Raymo111** [comment]
@elisemoe is it just me or should this issue be marked as verified 😅

**Comment by elisemoe** [comment]
> @elisemoe is it just me or should this issue be marked as verified 😅

Good catch 👍
