### ISSUE TITLE
Scavenger Hunt Entry: Lily Perry (@smiling_#4754 on discord)

### ISSUE THREAD

**Issue by LilyPerr** [education/hackconviii#21]
**Say hello 👋**
- [x] Yes, I have said hello to everyone I know at HackCon VIII

**Make new friends 👯‍♀️**
Share a screenshot of you introducing yourself to someone new.
We had a great conversation, and now she's gonna do the scavenger hunt too :)
![intro](https://user-images.githubusercontent.com/42851016/90968016-a6fc7d80-e4b5-11ea-8888-928b440865f9.png)

**Build your alter ego Octocat**
Please upload your Octocat here.
It's me at a hackathon!
![octocat](https://user-images.githubusercontent.com/42851016/90968018-afed4f00-e4b5-11ea-837c-576a2a4ace70.png)

**Screenshot selfie**
Upload the selfie of you and a GitHub team member or Campus Expert here.
![Screenshot (63)](https://user-images.githubusercontent.com/42851016/90981603-fed7ca80-e52f-11ea-8f2d-78553c1f3c18.png)

**Show us your "view" 🖼**
- [x] I've uploaded my view to the Discussion

**Where in the world? 🌍**
- [x] I've uploaded a picture to the Discussion

**Attend at least one lightning talk or panel featuring a Campus Expert ⚡️**
Which talk did you attend?
GitHub Lounge Activity: GitHub Engineering Q&A

Tell us a little bit about something you learned or were surprised by.
I was learned that even awesome Github employees deal with imposter syndrome. I also loved learning about Laura and Stephanie's paths in tech and how it brought them to where they are today.

🥚
Share a screenshot of what you found with `@elisemoe from Github` on Discord 😁 be sure to include your computer's clock in the screenshot to verify you've found the surprise yourself 🎉

- [x] I have shared a screenshot of the 🥚 with @elisemoe on Discord

**Comment by elisemoe** [comment]
Congrats @LilyPerr   ✨ You've completed your missions and can advance to the final stage 🎟. The GitHub stage! Please stop by the [GitHub Expo booth](https://app.hopin.to/events/hackcon-viii/expo/95842) anytime we’re not in session (or when the video is running) and request to share audio and video. We’ll invite you onto the stage and would love to either,

1. Hear your favorite programming joke, or
2. See your favorite dance move

If you don't hear from us right away, be sure to ping us in the #github-at-hackcon channel. Completion of this task will enter you into the raffle for scavenger hunt prizes.

See you there 💖
