### ISSUE TITLE
Scavenger Hunt Entry: hemant

### ISSUE THREAD

**Issue by mayhemantt** [education/hackconviii#23]
**Say hello 👋**
- [X] Yes, I have said hello to everyone I know at HackCon VIII

**Make new friends 👯‍♀️**
Share a screenshot of you introducing yourself to someone new.
![screencapture-discord-com-channels-me-746760149808578601-1598153756016](https://user-images.githubusercontent.com/62112099/90970243-f9728400-e51f-11ea-971b-64fd1e318db4.png)

**Build your alter ego Octocat**
Please upload your Octocat here.

![screencapture-myoctocat-com-build-your-octocat-1598153303277](https://user-images.githubusercontent.com/62112099/90970177-0478e480-e51f-11ea-8975-8d277102a349.png)

**Screenshot selfie**
Upload the selfie of you and a GitHub team member or Campus Expert here.
![Screenshot from 2020-08-23 09-34-12](https://user-images.githubusercontent.com/62112099/90970543-21fc7d00-e524-11ea-82fd-e7fada306738.png)

**Show us your "view" 🖼**
- [x] I've uploaded my view to the Discussion

![WhatsApp Image 2020-08-23 at 13 53 39](https://user-images.githubusercontent.com/62112099/90974374-2fc3f980-e548-11ea-9d91-14e1e2c67017.jpeg)

Attending Fire Side Chat: "GitHub India" was the best decision I made, where Dheraj and all the other mentors made the best experience and want to add a  rememberable statement " Be Ready To Learn and Unlearn"
**Where in the world? 🌍**
- [x] I've uploaded a picture to the Discussion

![905584-exjejhuwaaajtr](https://user-images.githubusercontent.com/62112099/90970326-32f7bf00-e521-11ea-857e-26680453d1a6.jpg)
 Attending from Uttarakhand India..

**Attend at least one lightning talk or panel featuring a Campus Expert ⚡️**
Which talk did you attend?
Tell us a little bit about something you learned or were surprised by.
I attended a session named Building a collaboration culture through CI/CD by Carlo Gilmar a Github CE. learned about the importance of communication and its benefits.
Also, I was really surprised to how great the campus ambassadors are they are  highly skilled and a lot helpful 

🥚
Share a screenshot of what you found with `@elisemoe from Github` on Discord 😁 be sure to include your computer's clock in the screenshot to verify you've found the surprise yourself 🎉

I found Mona, hidden and shared the screenshot with @elisemoe over discord.

- [x] I have shared a screenshot of the 🥚 with @elisemoe on Discord

**Comment by elisemoe** [comment]
Congrats @8bithemant   ✨ You've completed your missions and can advance to the final stage 🎟. The GitHub stage! Please stop by the [GitHub Expo booth](https://app.hopin.to/events/hackcon-viii/expo/95842) anytime we’re not in session (or when the video is running) and request to share audio and video. We’ll invite you onto the stage and would love to either,

1. Hear your favorite programming joke, or
2. See your favorite dance move

If you don't hear from us right away, be sure to ping us in the #github-at-hackcon channel. Completion of this task will enter you into the raffle for scavenger hunt prizes.

See you there 💖

**Comment by elisemoe** [comment]
Be sure to join us on stage before 12pm PT (in 1.5 hours) to enter the raffle! ✨
