### ISSUE TITLE
Scavenger Hunt Entry: Paul Horton

### ISSUE THREAD

**Issue by PaHorton** [education/hackconviii#24]
**Say hello 👋**
- [x] Yes, I have said hello to everyone I know at HackCon VIII

**Make new friends 👯‍♀️**
Share a screenshot of you introducing yourself to someone new.
![image](https://user-images.githubusercontent.com/13230281/90970560-7cadbe80-e4bb-11ea-95ef-49a0e96f16b6.png)

**Build your alter ego Octocat**
Please upload your Octocat here.
![octocat](https://user-images.githubusercontent.com/13230281/90970577-acf55d00-e4bb-11ea-8dec-ec13d9816dcb.png)

**Screenshot selfie**
Upload the selfie of you and a GitHub team member or Campus Expert here.
Does it count if she's right next to me?
![image](https://user-images.githubusercontent.com/13230281/90970579-b7aff200-e4bb-11ea-9a01-2a3a033bbb52.png)

**Show us your "view" 🖼**
- [x] I've uploaded my view to the Discussion

**Where in the world? 🌍**
- [x] I've uploaded a picture to the Discussion

**Attend at least one lightning talk or panel featuring a Campus Expert ⚡️**
Which talk did you attend?
Tell us a little bit about something you learned or were surprised by.

I attended @halcyonaura's talk, "Go the Hack To Sleep!" Being one of the people on her organizing team I can say with certainty that our hackathon desperately needs to stick to our sleep schedule. In the past, we would all stay up helping and hanging out until we would all pass out and one poor organizer would need to hold the fort through the night. I found her insights on making sure knowledge silos are broken down useful as this is also the case with our team. I really hope that we can implement her ideas to make sure our hackathon is successful this year :)

🥚
Share a screenshot of what you found with `@elisemoe from Github` on Discord 😁 be sure to include your computer's clock in the screenshot to verify you've found the surprise yourself 🎉

- [x] I have shared a screenshot of the 🥚 with @elisemoe on Discord

**Comment by elisemoe** [comment]
Congrats @PaHorton   ✨ You've completed your missions and can advance to the final stage 🎟. The GitHub stage! Please stop by the [GitHub Expo booth](https://app.hopin.to/events/hackcon-viii/expo/95842) anytime we’re not in session (or when the video is running) and request to share audio and video. We’ll invite you onto the stage and would love to either,

1. Hear your favorite programming joke, or
2. See your favorite dance move

If you don't hear from us right away, be sure to ping us in the #github-at-hackcon channel. Completion of this task will enter you into the raffle for scavenger hunt prizes.

See you there 💖

**Comment by elisemoe** [comment]
@PaHorton Be sure to join us on stage before 12pm PT (in 1.5 hours) to enter the raffle! ✨
