### ISSUE TITLE
Scavenger Hunt Entry: Radhika Sethi

### ISSUE THREAD

**Issue by radhikasethi2011** [education/hackconviii#25]
**Say hello 👋**
- [x] Yes, I have said hello to everyone I know at HackCon VIII

**Make new friends 👯‍♀️**
Share a screenshot of you introducing yourself to someone new.
![image](https://user-images.githubusercontent.com/44310177/90956667-47e33c80-e4a6-11ea-87fc-50999429b4dc.png)

**Build your alter ego Octocat**
Please upload your Octocat here.
![image](https://user-images.githubusercontent.com/44310177/90956794-4f571580-e4a7-11ea-97d0-c6cc5dacac3e.png)

**Screenshot selfie**
Upload the selfie of you and a GitHub team member or Campus Expert here.
![image](https://user-images.githubusercontent.com/44310177/90956806-65fd6c80-e4a7-11ea-819b-ab03e32db617.png)

**Show us your "view" 🖼**
- [x] I've uploaded my view to the Discussion

**Where in the world? 🌍**
- [x] I've uploaded a picture to the Discussion

**Attend at least one lightning talk or panel featuring a Campus Expert ⚡️**
Which talk did you attend?
Tell us a little bit about something you learned or were surprised by.
"Why hackers should continue hacking after becoming an organizer" - Harsha Srikara
What I learned - organizers have the following roles of Leadership, commitment, empowerment. But as an organizer, one shouldn't give up their original hobby of hacking, as well as create organizer meetups to boost the value of your community, for the other organizers that attend your hackathons. 

🥚
Share a screenshot of what you found with `@elisemoe from Github` on Discord 😁 be sure to include your computer's clock in the screenshot to verify you've found the surprise yourself 🎉

- [x] I have shared a screenshot of the 🥚 with @elisemoe on Discord

**Comment by elisemoe** [comment]
Congrats @radhikasethi2011   ✨ You've completed your missions and can advance to the final stage 🎟. The GitHub stage! Please stop by the [GitHub Expo booth](https://app.hopin.to/events/hackcon-viii/expo/95842) anytime we’re not in session (or when the video is running) and request to share audio and video. We’ll invite you onto the stage and would love to either,

1. Hear your favorite programming joke, or
2. See your favorite dance move

If you don't hear from us right away, be sure to ping us in the #github-at-hackcon channel. Completion of this task will enter you into the raffle for scavenger hunt prizes.

See you there 💖

**Comment by radhikasethi2011** [comment]
thank you!!!
