### ISSUE TITLE
Scavenger Hunt Entry: [HariOm Dwivedi]

### ISSUE THREAD

**Issue by HariOm987** [education/hackconviii#26]
**Say hello 👋**
- [x] Yes, I have said hello to everyone I know at HackCon VIII

**Make new friends 👯‍♀️**
Share a screenshot of you introducing yourself to someone new.
![image](https://user-images.githubusercontent.com/45634803/90981802-aed52400-e580-11ea-9bd5-172f66b11e61.png)

**Build your alter ego Octocat**
Please upload your Octocat here.
https://twitter.com/HariOmD10252521/status/1297543882524123137
![image](https://user-images.githubusercontent.com/45634803/90981859-f5c31980-e580-11ea-8889-f295e5a32c3c.png)

**Screenshot selfie**
Upload the selfie of you and a GitHub team member or Campus Expert here.
![image](https://user-images.githubusercontent.com/45634803/90981885-273be500-e581-11ea-88ab-91725814f5ab.png)

**Show us your "view" 🖼**
- [x] I've uploaded my view to the Discussion

**Where in the world? 🌍**
- [x] I've uploaded a picture to the Discussion

**Attend at least one lightning talk or panel featuring a Campus Expert ⚡️**
Which talk did you attend?
Tell us a little bit about something you learned or were surprised by.
I have attended talk event by Harsha Srikara and that was about how to lead any event and I learned many things regarding Leardership roles and some other sort of stuffs . XD
🥚
Share a screenshot of what you found with `@elisemoe from Github` on Discord 😁 be sure to include your computer's clock in the screenshot to verify you've found the surprise yourself 🎉

- [x] I have shared a screenshot of the 🥚 with @elisemoe on Discord

**Comment by HariOm987** [comment]
My selfie with MLH CEO and Co-founder Mike Swift sir
![image](https://user-images.githubusercontent.com/45634803/90982934-33777080-e588-11ea-8696-bcdb6614b8ad.png)

**Comment by elisemoe** [comment]
Congrats @HariOm987   ✨ You've completed your missions and can advance to the final stage 🎟. The GitHub stage! Please stop by the [GitHub Expo booth](https://app.hopin.to/events/hackcon-viii/expo/95842) anytime we’re not in session (or when the video is running) and request to share audio and video. We’ll invite you onto the stage and would love to either,

1. Hear your favorite programming joke, or
2. See your favorite dance move

If you don't hear from us right away, be sure to ping us in the #github-at-hackcon channel. Completion of this task will enter you into the raffle for scavenger hunt prizes.

See you there 💖
