### ISSUE TITLE
Scavenger Hunt Entry: [Gabe]

### ISSUE THREAD

**Issue by Garoto0518** [education/hackconviii#27]
**Say hello 👋**
- [x] Yes, I have said hello to everyone I know at HackCon VIII

**Make new friends 👯‍♀️**
Share a screenshot of you introducing yourself to someone new.
<img width="464" alt="Intro" src="https://user-images.githubusercontent.com/22475754/90984196-84b04180-e541-11ea-8b6e-7cf6f1718144.PNG">

**Build your alter ego Octocat**
Please upload your Octocat here.
![octocat](https://user-images.githubusercontent.com/22475754/90984219-a01b4c80-e541-11ea-8c95-f87a45849407.png)

**Screenshot selfie**
Upload the selfie of you and a GitHub team member or Campus Expert here.
Why not both? 
<img width="688" alt="Pic with member" src="https://user-images.githubusercontent.com/22475754/90985475-39e6f780-e54a-11ea-8320-2c36c92d2bf2.PNG">
<img width="666" alt="expert" src="https://user-images.githubusercontent.com/22475754/90985479-3bb0bb00-e54a-11ea-91ff-bdb96ed71830.PNG">

**Show us your "view" 🖼**
- [x] I've uploaded my view to the Discussion

**Where in the world? 🌍**
- [x] I've uploaded a picture to the Discussion

**Attend at least one lightning talk or panel featuring a Campus Expert ⚡️**
Which talk did you attend? Building A Strong Hackathon Brand Through Social Media by Neal Goyal
Tell us a little bit about something you learned or were surprised by.
I learned about the importance our social media account play with not only sponsors but attracting new hackers to be interested in out event. (The transition for this presentation was impeccable) 

🥚
Share a screenshot of what you found with `@elisemoe from Github` on Discord 😁 be sure to include your computer's clock in the screenshot to verify you've found the surprise yourself 🎉

- [x] I have shared a screenshot of the 🥚 with @elisemoe on Discord

**Comment by elisemoe** [comment]
Congrats @Garoto0518   ✨ You've completed your missions and can advance to the final stage 🎟. The GitHub stage! Please stop by the [GitHub Expo booth](https://app.hopin.to/events/hackcon-viii/expo/95842) anytime before **12pm PT today** that we’re not in session (or when the video is running) and request to share audio and video. We’ll invite you onto the stage and would love to either,

1. Hear your favorite programming joke, or
2. See your favorite dance move

If you don't hear from us right away, be sure to ping us in the #github-at-hackcon channel. Completion of this task will enter you into the raffle for scavenger hunt prizes.

See you there 💖
