### ISSUE TITLE
Scavenger Hunt Entry: Jobin Ayathil

### ISSUE THREAD

**Issue by 0xjba** [education/hackconviii#28]
**Say hello 👋**
- [X] Yes, I have said hello to everyone I know at HackCon VIII

**Make new friends 👯‍♀️**
Share a screenshot of you introducing yourself to someone new.
![photo6204168942012967631](https://user-images.githubusercontent.com/38902140/90984578-74c14d80-e593-11ea-9798-36730810958b.jpg)

**Build your alter ego Octocat**
Please upload your Octocat here.
![image](https://user-images.githubusercontent.com/38902140/90984604-99b5c080-e593-11ea-9bcf-bffd96fd14ec.png)

**Screenshot selfie**
Upload the selfie of you and a GitHub team member or Campus Expert here.
![photo6204168942012967632](https://user-images.githubusercontent.com/38902140/90984644-dda8c580-e593-11ea-8d4a-557bb8428b90.jpg)

**Show us your "view" 🖼**
- [X] I've uploaded my view to the Discussion

**Where in the world? 🌍**
- [X] I've uploaded a picture to the Discussion

**Attend at least one lightning talk or panel featuring a Campus Expert ⚡️**
Which talk did you attend?
Tell us a little bit about something you learned or were surprised by.
Attended the Lightning Talk by Anita Tse & Anna Arroyo. Got to know about the mentoring that the hackers can get & how to engage participants in hackathon especially guys from non-traditional backgrounds.

🥚
Share a screenshot of what you found with `@elisemoe from Github` on Discord 😁 be sure to include your computer's clock in the screenshot to verify you've found the surprise yourself 🎉
Mona-was-here & i, too was there!

- [X] I have shared a screenshot of the 🥚 with @elisemoe on Discord

**Comment by elisemoe** [comment]
Congrats @the-injineer  ✨ You've completed your missions and can advance to the final stage 🎟. The GitHub stage! Please stop by the [GitHub Expo booth](https://app.hopin.to/events/hackcon-viii/expo/95842) anytime before **12pm PT today** that we’re not in session (or when the video is running) and request to share audio and video. We’ll invite you onto the stage and would love to either,

1. Hear your favorite programming joke, or
2. See your favorite dance move

If you don't hear from us right away, be sure to ping us in the #github-at-hackcon channel. Completion of this task will enter you into the raffle for scavenger hunt prizes.

See you there 💖
