### ISSUE TITLE
Scavenger Hunt Entry: Nandini Sharma

### ISSUE THREAD

**Issue by nandinisharma3120** [education/hackconviii#6]
**Say hello 👋**
- [x] Yes, I have said hello to everyone I know at HackCon VIII

**Make new friends 👯‍♀️**
Share a screenshot of you introducing yourself to someone new.
![image](https://user-images.githubusercontent.com/46066660/90972689-0059c080-e539-11ea-9bb5-441ebd308e37.png)

**Build your alter ego Octocat**
Please upload your Octocat here.
![octocat](https://user-images.githubusercontent.com/46066660/90955475-52e49f80-e49b-11ea-9838-721193beba42.png)

**Screenshot selfie**
Upload the selfie of you and a GitHub team member or Campus Expert here.

![Screenshot (9)](https://user-images.githubusercontent.com/46066660/90959378-5d616200-e4b8-11ea-882c-2b3272b20777.png)

**Show us your "view" 🖼**
- [x] I've uploaded my view to the Discussion
![Screenshot (17)](https://user-images.githubusercontent.com/46066660/90976872-84726f00-e55e-11ea-8e84-885c938d29e7.png)

**Where in the world? 🌍**
- [x] I've uploaded a picture to the Discussion
![Screenshot (14)](https://user-images.githubusercontent.com/46066660/90976904-cb606480-e55e-11ea-8a9d-3ae63ded100b.png)

**Attend at least one lightning talk or panel featuring a Campus Expert ⚡️**
![Screenshot (17)](https://user-images.githubusercontent.com/46066660/90976872-84726f00-e55e-11ea-8e84-885c938d29e7.png)

Which talk did you attend?
Tell us a little bit about something you learned or were surprised by.
There are a lot of opportunities and there is a lot to learn. Rather than rushing over the success, we need to go after the knowledge.

- [x] 🥚

Share with us a screenshot of what you found 😁 be sure to include your computer's clock in the screenshot to verify you've found the surprise yourself 🎉

**Comment by elisemoe** [comment]
Congrats @idiosyncratic4   ✨ You've completed your missions and can advance to the final stage 🎟. The GitHub stage! Please stop by the [GitHub Expo booth](https://app.hopin.to/events/hackcon-viii/expo/95842) anytime before **12pm PT today** that we’re not in session (or when the video is running) and request to share audio and video. We’ll invite you onto the stage and would love to either,

1. Hear your favorite programming joke, or
2. See your favorite dance move

If you don't hear from us right away, be sure to ping us in the #github-at-hackcon channel. Completion of this task will enter you into the raffle for scavenger hunt prizes.

See you there 💖
