### ISSUE TITLE
Scavenger Hunt Entry: Sam Poder

### ISSUE THREAD

**Issue by sampoder** [education/hackconviii#7]
**Say hello 👋**
- [x] Yes, I have said hello to everyone I know at HackCon VIII

**Make new friends 👯‍♀️**
Share a screenshot of you introducing yourself to someone new.

very awkward intro ngl 

<img width="852" alt="Screenshot 2020-08-22 at 7 58 13 PM" src="https://user-images.githubusercontent.com/39828164/90955641-d14c3c00-e4b1-11ea-82cc-1d3b72e44f63.png">

**Build your alter ego Octocat**
Please upload your Octocat here.

![octocat](https://user-images.githubusercontent.com/39828164/90955945-b62efb80-e4b4-11ea-8738-46f35e349bc7.png)

**Screenshot selfie**
Upload the selfie of you and a GitHub team member or Campus Expert here.

was meant for my scrapbook buttt...

<img width="1440" alt="Screenshot 2020-08-22 at 9 04 28 AM" src="https://user-images.githubusercontent.com/39828164/90955650-ef19a100-e4b1-11ea-9e92-efd87c8f917b.png">

also this one with @juanpflores as well:

<img width="1440" alt="Screenshot 2020-08-22 at 8 56 13 PM" src="https://user-images.githubusercontent.com/39828164/90960787-b5a75c80-e4d6-11ea-8464-7994661fe9e7.png">
**Show us your "view" 🖼**
- [x] I've uploaded my view to the Discussion

**Where in the world? 🌍**
- [x] I've uploaded a picture to the Discussion

**Attend at least one lightning talk or panel featuring a Campus Expert ⚡️**

I attended the CI/CD talk given by Carlo Gilmar, alongside the wonderful illustrations I learnt all about the human aspect of CI/CD not just the software 😁😁😁

🥚

Share with us a screenshot of what you found 😁 be sure to include your computer's clock in the screenshot to verify you've found the surprise yourself 🎉

<img width="1440" alt="Screenshot 2020-08-23 at 12 17 55 AM" src="https://user-images.githubusercontent.com/39828164/90960819-ea1b1880-e4d6-11ea-99e3-ed429cb4a171.png">

**Comment by sampoder** [comment]
pls don't review yet, I'm still working on it

**Comment by sampoder** [comment]
@elisemoe I did it!! it's ready for review now

**Comment by elisemoe** [comment]
Congrats @sampoder  ✨ You've completed your missions and can advance to the final stage 🎟. The GitHub stage! Please stop by the [GitHub Expo booth](https://app.hopin.to/events/hackcon-viii/expo/95842) anytime we’re not in session (or when the video is running) and request to share audio and video. We’ll invite you onto the stage and would love to either,

1. Hear your favorite program joke, or
2. See your favorite dance move

Completion of this task will enter you into the raffle for scavenger hunt prizes.

See you there 💖
